### ISSUE TITLE
How to setup cluster with multiple servers

### ISSUE THREAD

**Issue by hoabka** [RTCEngine/coturn-cluster#1]
Hello Mr. Leeoxiang,
I would like to setup cluster with multiple coturn servers for high avalibility.
As I know, you setup multiple coturn process running on same server. 
I not yet understand how you can setup the endpoint to balance traffic to cluster with multiple servers separately?
In case I wanna setup a LoadBalancer (like LB of AWS) in front of cluster. Is it possible?
Any recommendation greatly appreciate.
Thank you

**Comment by notedit** [comment]
LoadBalancer  is  useless for coturn,  coturn server does not know the real ip of the user.

**Comment by notedit** [comment]
coturn use  'alternate-server'  for loadbanlance.

**Comment by hoabka** [comment]
Thank you for your kindly support. I already found the another way to rebalance among coturn servers by using Zookeeper and LoadDistriubter server implemented by ourself. Using alternative servers is another way but it is hard to scale out elasticitic, I think
